# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 600)
        MainWindow.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(90, 90, 134);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"/* HANDLEBAR VERTICAL */\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(60, 60, 90);\n"
"    min-width:30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {\n"
"    background-color: rgb(220, 0, 110);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border:none;\n"
"    background-color: rgb(60, 60, 90);\n"
"    height: 15px;\n"
"    border-top-left-radius:7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position:top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"    background-color: rgb(220, 0, 110);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border:none;\n"
"    background-color: rgb(60, 60, 90);\n"
"    height: 15px;\n"
"    border-bottom-left-radius:7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position:bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {\n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"    background-color: rgb(220, 0, 110);\n"
"}\n"
"\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background:none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background:none;\n"
"}\n"
"\n"
"\n"
"/* */\n"
"/* VERTICAL SCROLLBAR */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(90, 90, 134);\n"
"    height: 14px;\n"
"    margin: 0 15px 0 15px;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"/* HANDLEBAR VERTICAL */\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(60, 60, 90);\n"
"    min-height:30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {\n"
"    background-color: rgb(220, 0, 110);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border:none;\n"
"    background-color: rgb(60, 60, 90);\n"
"    width: 15px;\n"
"    border-top-left-radius:7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position:left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"    background-color: rgb(220, 0, 110);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border:none;\n"
"    background-color: rgb(60, 60, 90);\n"
"    width: 15px;\n"
"    border-top-right-radius:7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position:right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {\n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {\n"
"    background-color: rgb(220, 0, 110);\n"
"}\n"
"\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    background:none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background:none;\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TotalFrame = QtWidgets.QFrame(self.centralwidget)
        self.TotalFrame.setGeometry(QtCore.QRect(0, 0, 450, 600))
        self.TotalFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.TotalFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.TotalFrame.setObjectName("TotalFrame")
        self.selectPathButton = QtWidgets.QPushButton(self.TotalFrame)
        self.selectPathButton.setGeometry(QtCore.QRect(330, 100, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.selectPathButton.setFont(font)
        self.selectPathButton.setStyleSheet("QPushButton {\n"
"    color:#FFFFFF;\n"
"    border-radius:10px;\n"
"    background-color: rgb(115, 115, 171);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:#FFFFFF;\n"
"    border-radius:10px;\n"
"    background-color: rgb(146, 146, 217);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color:#FFFFFF;\n"
"    border-radius:10px;\n"
"    background-color: rgb(125, 125, 185);\n"
"}")
        self.selectPathButton.setObjectName("selectPathButton")
        self.ExtractPathButton = QtWidgets.QPushButton(self.TotalFrame)
        self.ExtractPathButton.setGeometry(QtCore.QRect(330, 140, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ExtractPathButton.setFont(font)
        self.ExtractPathButton.setStyleSheet("QPushButton {\n"
"    color:#FFFFFF;\n"
"    border-radius:10px;\n"
"    background-color: rgb(115, 115, 171);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:#FFFFFF;\n"
"    border-radius:10px;\n"
"    background-color: rgb(146, 146, 217);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color:#FFFFFF;\n"
"    border-radius:10px;\n"
"    background-color: rgb(125, 125, 185);\n"
"}")
        self.ExtractPathButton.setObjectName("ExtractPathButton")
        self.LEFormat = QtWidgets.QLineEdit(self.TotalFrame)
        self.LEFormat.setGeometry(QtCore.QRect(240, 140, 81, 31))
        self.LEFormat.setObjectName("LEFormat")
        self.comboBoxSelectMenu = QtWidgets.QComboBox(self.TotalFrame)
        self.comboBoxSelectMenu.setGeometry(QtCore.QRect(20, 140, 211, 31))
        self.comboBoxSelectMenu.setObjectName("comboBoxSelectMenu")
        self.comboBoxSelectMenu.addItem("")
        self.comboBoxSelectMenu.addItem("")
        self.PathLE = QtWidgets.QLineEdit(self.TotalFrame)
        self.PathLE.setGeometry(QtCore.QRect(20, 100, 301, 31))
        self.PathLE.setReadOnly(True)
        self.PathLE.setObjectName("PathLE")
        self.frame = QtWidgets.QFrame(self.TotalFrame)
        self.frame.setGeometry(QtCore.QRect(10, 10, 430, 580))
        self.frame.setStyleSheet("background-color: rgb(53, 53, 79);\n"
"border-radius: 20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.TE_Log = QtWidgets.QTextEdit(self.TotalFrame)
        self.TE_Log.setGeometry(QtCore.QRect(20, 220, 411, 271))
        self.TE_Log.setStyleSheet("border-radius:15px;")
        self.TE_Log.setObjectName("TE_Log")
        self.QuitBotton = QtWidgets.QPushButton(self.TotalFrame)
        self.QuitBotton.setGeometry(QtCore.QRect(400, 20, 30, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.QuitBotton.setFont(font)
        self.QuitBotton.setStyleSheet("QPushButton {\n"
"    color:#FFFFFF;\n"
"    border-bottom-right-radius:15px;\n"
"    border-top-right-radius: 15px;\n"
"    background-color: rgb(115, 115, 171);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:#FFFFFF;\n"
"    border-bottom-right-radius:15px;\n"
"    border-top-right-radius: 15px;\n"
"    background-color: rgb(146, 146, 217);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color:#FFFFFF;\n"
"    border-bottom-right-radius:15px;\n"
"    border-top-right-radius: 15px;\n"
"    background-color: rgb(125, 125, 185);\n"
"}\n"
"\n"
"")
        self.QuitBotton.setObjectName("QuitBotton")
        self.label = QtWidgets.QLabel(self.TotalFrame)
        self.label.setGeometry(QtCore.QRect(20, 190, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.TitleLabel = QtWidgets.QLabel(self.TotalFrame)
        self.TitleLabel.setGeometry(QtCore.QRect(20, 20, 340, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setStyleSheet("    color:#FFFFFF;\n"
"    border-bottom-left-radius:15px;\n"
"    border-top-left-radius: 15px;\n"
"    background-color: rgb(115, 115, 171);")
        self.TitleLabel.setObjectName("TitleLabel")
        self.label_2 = QtWidgets.QLabel(self.TotalFrame)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.TotalFrame)
        self.line.setGeometry(QtCore.QRect(20, 170, 411, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.TotalFrame)
        self.line_2.setGeometry(QtCore.QRect(20, 50, 411, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.TotalFrame)
        self.line_3.setGeometry(QtCore.QRect(20, 490, 411, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.RunFunctionLabel = QtWidgets.QLabel(self.TotalFrame)
        self.RunFunctionLabel.setGeometry(QtCore.QRect(20, 510, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.RunFunctionLabel.setFont(font)
        self.RunFunctionLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.RunFunctionLabel.setObjectName("RunFunctionLabel")
        self.comboBoxSelectFunction = QtWidgets.QComboBox(self.TotalFrame)
        self.comboBoxSelectFunction.setEnabled(True)
        self.comboBoxSelectFunction.setGeometry(QtCore.QRect(20, 540, 301, 31))
        self.comboBoxSelectFunction.setObjectName("comboBoxSelectFunction")
        self.RunFuncButton = QtWidgets.QPushButton(self.TotalFrame)
        self.RunFuncButton.setEnabled(True)
        self.RunFuncButton.setGeometry(QtCore.QRect(330, 540, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.RunFuncButton.setFont(font)
        self.RunFuncButton.setStyleSheet("QPushButton {\n"
"    color:#FFFFFF;\n"
"    border-radius:10px;\n"
"    background-color: rgb(115, 115, 171);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:#FFFFFF;\n"
"    border-radius:10px;\n"
"    background-color: rgb(146, 146, 217);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color:#FFFFFF;\n"
"    border-radius:10px;\n"
"    background-color: rgb(125, 125, 185);\n"
"}")
        self.RunFuncButton.setObjectName("RunFuncButton")
        self.InSettingButton = QtWidgets.QPushButton(self.TotalFrame)
        self.InSettingButton.setGeometry(QtCore.QRect(365, 20, 32, 32))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.InSettingButton.setFont(font)
        self.InSettingButton.setStyleSheet("QPushButton {\n"
"    color:#FFFFFF;\n"
"    background-color: rgb(115, 115, 171);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:#FFFFFF;\n"
"    background-color: rgb(146, 146, 217);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color:#FFFFFF;\n"
"    background-color: rgb(125, 125, 185);\n"
"}\n"
"\n"
"")
        self.InSettingButton.setObjectName("InSettingButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.TotalFrame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(330, 510, 101, 21))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.toggleLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.toggleLayout.setContentsMargins(0, 0, 0, 0)
        self.toggleLayout.setObjectName("toggleLayout")
        self.frame.raise_()
        self.selectPathButton.raise_()
        self.ExtractPathButton.raise_()
        self.LEFormat.raise_()
        self.comboBoxSelectMenu.raise_()
        self.PathLE.raise_()
        self.TE_Log.raise_()
        self.QuitBotton.raise_()
        self.label.raise_()
        self.TitleLabel.raise_()
        self.label_2.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.RunFunctionLabel.raise_()
        self.comboBoxSelectFunction.raise_()
        self.RunFuncButton.raise_()
        self.InSettingButton.raise_()
        self.verticalLayoutWidget.raise_()
        self.SettingMainFrame = QtWidgets.QFrame(self.centralwidget)
        self.SettingMainFrame.setGeometry(QtCore.QRect(0, 150, 450, 270))
        self.SettingMainFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.SettingMainFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.SettingMainFrame.setObjectName("SettingMainFrame")
        self.SetOptionOuterFrame = QtWidgets.QFrame(self.SettingMainFrame)
        self.SetOptionOuterFrame.setGeometry(QtCore.QRect(10, 5, 430, 260))
        self.SetOptionOuterFrame.setStyleSheet("background-color: rgb(214, 0, 107);\n"
"border-radius: 20px;")
        self.SetOptionOuterFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.SetOptionOuterFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.SetOptionOuterFrame.setObjectName("SetOptionOuterFrame")
        self.frame_3 = QtWidgets.QFrame(self.SetOptionOuterFrame)
        self.frame_3.setGeometry(QtCore.QRect(5, 5, 420, 250))
        self.frame_3.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.SettingQuitBotton = QtWidgets.QPushButton(self.frame_3)
        self.SettingQuitBotton.setGeometry(QtCore.QRect(385, 5, 30, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SettingQuitBotton.setFont(font)
        self.SettingQuitBotton.setStyleSheet("QPushButton {\n"
"    color:#FFFFFF;\n"
"    border-bottom-right-radius:15px;\n"
"    border-top-right-radius: 15px;\n"
"    background-color: rgb(115, 115, 171);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:#FFFFFF;\n"
"    border-bottom-right-radius:15px;\n"
"    border-top-right-radius: 15px;\n"
"    background-color: rgb(146, 146, 217);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color:#FFFFFF;\n"
"    border-bottom-right-radius:15px;\n"
"    border-top-right-radius: 15px;\n"
"    background-color: rgb(125, 125, 185);\n"
"}\n"
"\n"
"")
        self.SettingQuitBotton.setObjectName("SettingQuitBotton")
        self.SettingStackedWidget = QtWidgets.QStackedWidget(self.SettingMainFrame)
        self.SettingStackedWidget.setGeometry(QtCore.QRect(23, 190, 401, 61))
        self.SettingStackedWidget.setObjectName("SettingStackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.line_6 = QtWidgets.QFrame(self.page)
        self.line_6.setGeometry(QtCore.QRect(0, -20, 16, 81))
        self.line_6.setStyleSheet("")
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_6.setLineWidth(3)
        self.line_6.setMidLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_6.setObjectName("line_6")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(53, 53, 79);")
        self.label_7.setObjectName("label_7")
        self.LE_SkipCount = QtWidgets.QLineEdit(self.page)
        self.LE_SkipCount.setGeometry(QtCore.QRect(220, 20, 81, 21))
        self.LE_SkipCount.setObjectName("LE_SkipCount")
        self.SettingStackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.line_7 = QtWidgets.QFrame(self.page_2)
        self.line_7.setGeometry(QtCore.QRect(0, -10, 16, 81))
        self.line_7.setStyleSheet("")
        self.line_7.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_7.setLineWidth(3)
        self.line_7.setMidLineWidth(2)
        self.line_7.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_7.setObjectName("line_7")
        self.LE_StartCount = QtWidgets.QLineEdit(self.page_2)
        self.LE_StartCount.setGeometry(QtCore.QRect(100, 20, 31, 21))
        self.LE_StartCount.setObjectName("LE_StartCount")
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(53, 53, 79);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setGeometry(QtCore.QRect(150, 10, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(53, 53, 79);")
        self.label_9.setObjectName("label_9")
        self.line_8 = QtWidgets.QFrame(self.page_2)
        self.line_8.setGeometry(QtCore.QRect(130, -10, 16, 81))
        self.line_8.setStyleSheet("")
        self.line_8.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_8.setLineWidth(3)
        self.line_8.setMidLineWidth(2)
        self.line_8.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_8.setObjectName("line_8")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.page_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(310, 10, 81, 41))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.addWorkUncertainLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.addWorkUncertainLayout.setContentsMargins(0, 0, 0, 0)
        self.addWorkUncertainLayout.setObjectName("addWorkUncertainLayout")
        self.SettingStackedWidget.addWidget(self.page_2)
        self.label_3 = QtWidgets.QLabel(self.SettingMainFrame)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(53, 53, 79);")
        self.label_3.setObjectName("label_3")
        self.selectPathButton_runFunctionResDir = QtWidgets.QPushButton(self.SettingMainFrame)
        self.selectPathButton_runFunctionResDir.setGeometry(QtCore.QRect(330, 150, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.selectPathButton_runFunctionResDir.setFont(font)
        self.selectPathButton_runFunctionResDir.setStyleSheet("QPushButton {\n"
"    color:#FFFFFF;\n"
"    border-radius:10px;\n"
"    background-color: rgb(115, 115, 171);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:#FFFFFF;\n"
"    border-radius:10px;\n"
"    background-color: rgb(146, 146, 217);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color:#FFFFFF;\n"
"    border-radius:10px;\n"
"    background-color: rgb(125, 125, 185);\n"
"}")
        self.selectPathButton_runFunctionResDir.setObjectName("selectPathButton_runFunctionResDir")
        self.selectPathButton_ExtractSubDirPath = QtWidgets.QPushButton(self.SettingMainFrame)
        self.selectPathButton_ExtractSubDirPath.setGeometry(QtCore.QRect(330, 80, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.selectPathButton_ExtractSubDirPath.setFont(font)
        self.selectPathButton_ExtractSubDirPath.setStyleSheet("QPushButton {\n"
"    color:#FFFFFF;\n"
"    border-radius:10px;\n"
"    background-color: rgb(115, 115, 171);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:#FFFFFF;\n"
"    border-radius:10px;\n"
"    background-color: rgb(146, 146, 217);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color:#FFFFFF;\n"
"    border-radius:10px;\n"
"    background-color: rgb(125, 125, 185);\n"
"}")
        self.selectPathButton_ExtractSubDirPath.setObjectName("selectPathButton_ExtractSubDirPath")
        self.LE_Setting_RunFunctionDir = QtWidgets.QLineEdit(self.SettingMainFrame)
        self.LE_Setting_RunFunctionDir.setGeometry(QtCore.QRect(40, 150, 281, 31))
        self.LE_Setting_RunFunctionDir.setReadOnly(True)
        self.LE_Setting_RunFunctionDir.setObjectName("LE_Setting_RunFunctionDir")
        self.LE_Setting_ExtractSubDirFileName = QtWidgets.QLineEdit(self.SettingMainFrame)
        self.LE_Setting_ExtractSubDirFileName.setGeometry(QtCore.QRect(230, 80, 91, 31))
        self.LE_Setting_ExtractSubDirFileName.setObjectName("LE_Setting_ExtractSubDirFileName")
        self.line_4 = QtWidgets.QFrame(self.SettingMainFrame)
        self.line_4.setGeometry(QtCore.QRect(30, 50, 3, 61))
        self.line_4.setStyleSheet("background-color: rgb(53, 53, 79);")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_4.setLineWidth(3)
        self.line_4.setMidLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_4.setObjectName("line_4")
        self.label_4 = QtWidgets.QLabel(self.SettingMainFrame)
        self.label_4.setGeometry(QtCore.QRect(40, 60, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(53, 53, 79);")
        self.label_4.setObjectName("label_4")
        self.line_5 = QtWidgets.QFrame(self.SettingMainFrame)
        self.line_5.setGeometry(QtCore.QRect(30, 120, 3, 61))
        self.line_5.setStyleSheet("background-color: rgb(53, 53, 79);")
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_5.setLineWidth(3)
        self.line_5.setMidLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_5.setObjectName("line_5")
        self.LE_Setting_ExtractSubDirPath = QtWidgets.QLineEdit(self.SettingMainFrame)
        self.LE_Setting_ExtractSubDirPath.setGeometry(QtCore.QRect(40, 80, 181, 31))
        self.LE_Setting_ExtractSubDirPath.setReadOnly(True)
        self.LE_Setting_ExtractSubDirPath.setObjectName("LE_Setting_ExtractSubDirPath")
        self.label_5 = QtWidgets.QLabel(self.SettingMainFrame)
        self.label_5.setGeometry(QtCore.QRect(230, 60, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(53, 53, 79);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.SettingMainFrame)
        self.label_6.setGeometry(QtCore.QRect(40, 130, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(53, 53, 79);")
        self.label_6.setObjectName("label_6")
        self.CustomRunButton = QtWidgets.QPushButton(self.centralwidget)
        self.CustomRunButton.setGeometry(QtCore.QRect(175, 430, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.CustomRunButton.setFont(font)
        self.CustomRunButton.setStyleSheet("QPushButton {\n"
"    color:#FFFFFF;\n"
"    border-radius:50px;\n"
"    background-color: rgb(115, 115, 171);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:#FFFFFF;\n"
"    border-radius:50px;\n"
"    background-color: rgb(146, 146, 217);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color:#FFFFFF;\n"
"    border-radius:50px;\n"
"    background-color: rgb(125, 125, 185);\n"
"}")
        self.CustomRunButton.setObjectName("CustomRunButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.SettingStackedWidget.setCurrentIndex(0)
        self.SettingQuitBotton.clicked.connect(self.SettingMainFrame.hide)
        self.InSettingButton.clicked.connect(self.SettingMainFrame.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HyenaProject"))
        self.selectPathButton.setText(_translate("MainWindow", "Select Path"))
        self.ExtractPathButton.setText(_translate("MainWindow", "Run"))
        self.comboBoxSelectMenu.setItemText(0, _translate("MainWindow", "Extract Lower Dir"))
        self.comboBoxSelectMenu.setItemText(1, _translate("MainWindow", "Count File Num"))
        self.QuitBotton.setText(_translate("MainWindow", "x"))
        self.label.setText(_translate("MainWindow", "Log"))
        self.TitleLabel.setText(_translate("MainWindow", "   HN Program"))
        self.label_2.setText(_translate("MainWindow", "Pretreatment"))
        self.RunFunctionLabel.setText(_translate("MainWindow", "Run Function"))
        self.RunFuncButton.setText(_translate("MainWindow", "Run Default"))
        self.InSettingButton.setText(_translate("MainWindow", "?"))
        self.SettingQuitBotton.setText(_translate("MainWindow", "x"))
        self.label_7.setText(_translate("MainWindow", "SkipCount per Search Dir"))
        self.LE_StartCount.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Start Count"))
        self.label_9.setText(_translate("MainWindow", "AddWork Uncertain List"))
        self.label_3.setText(_translate("MainWindow", "Setting"))
        self.selectPathButton_runFunctionResDir.setText(_translate("MainWindow", "Modify.."))
        self.selectPathButton_ExtractSubDirPath.setText(_translate("MainWindow", "Modify.."))
        self.label_4.setText(_translate("MainWindow", "Extract SubDir Path"))
        self.label_5.setText(_translate("MainWindow", "File Name"))
        self.label_6.setText(_translate("MainWindow", "Run Function Result Save Dir"))
        self.CustomRunButton.setText(_translate("MainWindow", "Run!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
